### PR TITLE
Removing quotes while executing few aci related shell commands

### PR DESCRIPTION
**Pull request by gaurav-dalvi**

### CODE REVIEW

**Comment by apoorva11029** [comment]
LGTM

**Comment by snaiksat** [comment]
Had a chat with Apoorva as to why we thought this was working before but its failing now. I believe the suspicion is that the ansible version is at play. So will the above change fix it one version versus break it in another the version that we had successfully tested on before? (If the ansible version theory is true, its most likely that the versions are different for 3.10 versus 3.11, but we do need to support both.)

**Comment by gaurav-dalvi** [comment]
```

openshift-ansible]# oc get namespaces
NAME                    STATUS    AGE
aci-containers-system   Active    2h
default                 Active    2h
kube-proxy-and-dns      Active    2h
kube-public             Active    2h
kube-service-catalog    Active    2h
kube-system             Active    2h
management-infra        Active    2h
openshift               Active    2h
openshift-console       Active    2h
openshift-infra         Active    2h
openshift-monitoring    Active    2h
openshift-node          Active    2h
openshift-web-console   Active    2h
[root@vos-1-rh-25-1 openshift-ansible]# oc describe namespace openshift-web-console
Name:         openshift-web-console
Labels:       <none>
Annotations:  openshift.io/description=
              openshift.io/display-name=
              openshift.io/sa.scc.mcs=s0:c10,c5
              openshift.io/sa.scc.supplemental-groups=1000100000/10000
              openshift.io/sa.scc.uid-range=1000100000/10000
              opflex.cisco.com/endpoint-group={"policy-space":"vos1", "name": "kubernetes|kube-system"}
Status:       Active

No resource quota.

No resource limits.
[root@vos-1-rh-25-1 openshift-ansible]# oc describe namespace kube-service-catalog
Name:         kube-service-catalog
Labels:       <none>
Annotations:  openshift.io/description=
              openshift.io/display-name=
              openshift.io/sa.scc.mcs=s0:c11,c0
              openshift.io/sa.scc.supplemental-groups=1000110000/10000
              openshift.io/sa.scc.uid-range=1000110000/10000
              opflex.cisco.com/endpoint-group={"policy-space":"vos1", "name": "kubernetes|kube-system"}
Status:       Active

No resource quota.

No resource limits.
[root@vos-1-rh-25-1 openshift-ansible]# oc describe namespace openshift-monitoring
Name:         openshift-monitoring
Labels:       <none>
Annotations:  openshift.io/description=
              openshift.io/display-name=
              openshift.io/sa.scc.mcs=s0:c10,c0
              openshift.io/sa.scc.supplemental-groups=1000090000/10000
              openshift.io/sa.scc.uid-range=1000090000/10000
              opflex.cisco.com/endpoint-group={"policy-space":"vos1", "name": "kubernetes|kube-system"}
Status:       Active

No resource quota.

No resource limits.
[root@vos-1-rh-25-1 openshift-ansible]#
````

**Review by snaiksat — APPROVED** [review]

**Comment by puppet-py** [comment]
Minor comment: why are we copying the file to /tmp, can we not execute at the src ?
Otherwise LGTM !

**Pull request merged**
